---
name: Feature request
description: Suggest an idea for this project. 支持中文。
title: "[Feat]: "
labels: ["feat"]
assignees:
  - alanhg
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feat request!
  - type: textarea
    id: why-need
    attributes:
      label: Describe the need
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
    validations:
      required: true
  - type: dropdown
    id: workflow-name
    attributes:
      label: Workflow Name
      description: >
        if it's new workflow need. Don't have to choose.
      options:
        - 2FA-Read Code
        - About Mac
        - Airdrop
        - AppID
        - AppleScript Tools
        - Batch Import Workflows
        - Bluetooth Manager
        - Brightness Control
        - ChatGPT Enhancer
        - Clipboard History
        - Compress
        - ConvertIO
        - Copy Files to The frontmost Finder
        - DO NOT DISTURB
        - Eudic Tools
        - File Enhancer
        - Find iPhone
        - Giphy
        - Git Code
        - Resize Image
        - IP Tools
        - JSON View
        - Json2TS
        - Local Network
        - Mac Enhancer
        - Medium Tools
        - Meeting
        - Mount Volume
        - Multimedia Convert
        - My iPhones
        - New File
        - OCR
        - Open Chrome Profile
        - OpenConnect VPN
        - Paste into files
        - PDF Converter
        - Pic Uploader
        - Process
        - ProgressBar
        - QR Reader
        - Generate Image
        - Alfred Remote
        - RGB-Hex converter
        - SQL Formatter
        - SSH Utils
        - String Manipulation
        - Surge
        - Switch Audio
        - System Settings
        - Translate
        - Type Search
        - UAParser
        - video
        - Whistle
        - 印象笔记
    validations:
      required: false
